### ISSUE TITLE
encountered an error while doing ng serve for the project which u gave yesterday 

### ISSUE THREAD

**Issue by khasimhk** [training-jyas/angular-weekday-2#6]
![error1](https://user-images.githubusercontent.com/25627721/31043698-24decab0-a5de-11e7-96e4-e79721af4b6c.png)

**Comment by khasimhk** [comment]
please check the error once

**Comment by khasimhk** [comment]
we hav struck in the serve itself

**Comment by jyasveer** [comment]
sorry for this. now you can take the latest and try.
